import os

BASE_URL = "https://api.siperb.com"
TRIAL_HOURS = 1
TRIAL_MINUTES = 15
EXPIRING_SOON_DAYS = 3
REGISTRAR_PORT = 5060
TRANSPORT_TYPE = "udp"
SBC_HOST = "eu-west-1-sbc-1.siperb.com"
PBX_PASSWORD = "Office@11"

# Siperb PAT (same as EXE — base64-encoded, identical to V6 client.py)
ENCODED_PAT = "Yjg2NmFlNDg2Mjk2ZjgwNGQxMzFmNjg5NmFjNjgwYmVmZmYxMDA5OGIyODBlNmU4M2RhNGRmMDI1MDBkOWRmY2JlNzM3M2U1OGYxNDI1MTNhYmQ1NWZmNjhmMzg4MjkzMmY3NzI0NmU4Nzc3MDU1Nzg1ZGM4MDkwODViMjIzNjkxOGMyNTZlZDA3OTVjMTY3ZDVkNmEzZTBkMmMwYWQwNGExODZkMzFlZTEzZWZkZDg1MzczNDkyYWY4M2RmZDJjN2NhMjRlN2MwMzJkMjZkMzY0OGUyN2Y4ZGZlNjI4ZjgwZTRkNDdlMTU0ZmM0OWM3MTlmYmQ3ZjY0ODMyMjJlOA=="

# Real secrets — must be set via Streamlit Cloud Secrets or env vars
RESEND_API_KEY = os.environ.get("RESEND_API_KEY")
SENDER_EMAIL = os.environ.get("SENDER_EMAIL")
CONNEXCS_USERNAME = os.environ.get("CONNEXCS_USERNAME")
CONNEXCS_PASSWORD = os.environ.get("CONNEXCS_PASSWORD")
